name: Conda Build

# This workflow is triggered on pushes or pull request to the repository.
on:
  push:
    # file paths to consider in the event. Optional; defaults to all.
    paths:
      - 'ci/**'
      - 'cpp/**'
      - 'python/**'
      - 'spark/**'
      - 'conda/**'
      - '.github/workflows/conda_build.yml'
      - '!**.md'
      - '!ci/jenkins/**'
  pull_request:
    # file paths to consider in the event. Optional; defaults to all.
    paths:
      - 'ci/**'
      - 'cpp/**'
      - 'python/**'
      - 'spark/**'
      - '.github/workflows/conda_build.yml'
      - '!**.md'
      - '!ci/jenkins/**'

jobs:
  centos:
    name: ${{ matrix.title }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        name:
          - conda-python3.6
          - conda-python3.7
          - conda-python3.6-cuda
          - conda-python3.7-cuda
        include:
          - name: conda-python3.6
            condapy: 36
            centos: 7
            service: conda-build
            title: AMD64 CentOS 7 Conda Python 3.6
          - name: conda-python3.7
            condapy: 37
            centos: 7
            service: conda-build
            title: AMD64 CentOS 7 Conda Python 3.7
          - name: conda-python3.6-cuda
            condapy: 36
            centos: 7
            service: conda-cudagl-build
            title: AMD64 CentOS 7 Conda Python 3.6 CUDA
          - name: conda-python3.7-cuda
            condapy: 37
            centos: 7
            service: conda-cudagl-build
            title: AMD64 CentOS 7 Conda Python 3.7 CUDA
    env:
      CENTOS: ${{ matrix.centos || 7 }}
      CONDA_PY: ${{ matrix.condapy || 37 }}
    steps:
      # This step checks out a copy of your repository.
      - name: Checkout Arctern
        uses: actions/checkout@v1
      - name: Docker Pull
        shell: bash
        run: |
          docker-compose pull --ignore-pull-failures ${{ matrix.service }}
      - name: Docker Build
        shell: bash
        run: |
          docker-compose build ${{ matrix.service }}
      - name: Docker Run
        run: |
          docker-compose run -e GIT_BRANCH=${GITHUB_REF##*/} \
                             -e CONDA_USERNAME=arctern-dev \
                             -e MY_UPLOAD_KEY=${{ secrets.DEV_ANACONDA_TOKEN }} \
                             ${{ matrix.service }}
      - name: Docker Push
        if: success() && github.event_name == 'push' && github.repository == 'zilliztech/arctern'
        continue-on-error: true
        shell: bash
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USER }} \
                       -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker-compose push ${{ matrix.service }}
